spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: validate
dgc:
  proxy:
    host: sia-lb.telekom.de
    port: 8080
  # Define your own steps to import data or use a prepared workflow
  import-job-steps: []
